// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJo9twgISVi7C6NIFeJUZIgtt8JdHkqU0',
    appId: '1:296101824731:web:6e6bdfda1ad6a63e0ee4fe',
    messagingSenderId: '296101824731',
    projectId: 'relationship-xp-f60c8',
    authDomain: 'relationship-xp-f60c8.firebaseapp.com',
    storageBucket: 'relationship-xp-f60c8.firebasestorage.app',
    measurementId: 'G-RLFEW3S9S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf7IqUPIu9c3-bntSG4SE7wxSZpS1WEO8',
    appId: '1:296101824731:android:a8407b3708b08daf0ee4fe',
    messagingSenderId: '296101824731',
    projectId: 'relationship-xp-f60c8',
    storageBucket: 'relationship-xp-f60c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa3o4qJt7D6BqEHOTT4jUy5V4HhCMtLLM',
    appId: '1:296101824731:ios:57e2e7b84f4901940ee4fe',
    messagingSenderId: '296101824731',
    projectId: 'relationship-xp-f60c8',
    storageBucket: 'relationship-xp-f60c8.firebasestorage.app',
    iosBundleId: 'com.example.flutterRelationshipXp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa3o4qJt7D6BqEHOTT4jUy5V4HhCMtLLM',
    appId: '1:296101824731:ios:57e2e7b84f4901940ee4fe',
    messagingSenderId: '296101824731',
    projectId: 'relationship-xp-f60c8',
    storageBucket: 'relationship-xp-f60c8.firebasestorage.app',
    iosBundleId: 'com.example.flutterRelationshipXp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJo9twgISVi7C6NIFeJUZIgtt8JdHkqU0',
    appId: '1:296101824731:web:6b6dd707738773bf0ee4fe',
    messagingSenderId: '296101824731',
    projectId: 'relationship-xp-f60c8',
    authDomain: 'relationship-xp-f60c8.firebaseapp.com',
    storageBucket: 'relationship-xp-f60c8.firebasestorage.app',
    measurementId: 'G-9TWBXFMGM1',
  );
}
